name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger the action on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use the Node.js version required for your project

    - name: Install dependencies
      run: npm install

    - name: Install gh-pages
      run: npm install gh-pages --save-dev

    - name: Build the project
      run: npm run build

    # Set up Git user before deploying
    - name: Configure Git user
      run: |
        git config --global user.name "revanth7999"
        git config --global user.email "revanthkumar.iris@gmail.com"

    - name: Deploy to GitHub Pages
      run: npx gh-pages -d dist -f --repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/revanth7999/dinemaster-ui.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
